services:

  postgres:
    image: postgres
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 3s
      timeout: 0s
      retries: 30


#   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#   README! UNCOMMENT postgres-start-scripts below unless LAUNCHING IT FOR THE FIRST TIME!
#   IT WILL INITIALIZE AN AIRFLOW DATABASE FOR AIRFLOW SCHEDULER
#   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#  postgres-start-scripts:
#    container_name: postgres_start_script
#    image: timescale/timescaledb-ha:pg15
#    depends_on:
#      postgres:
#        condition: service_healthy
#    # Some seeding
#    command:
#      - 'bash'
#      - '-c'
#      - |
#        PGPASSWORD=postgres psql -h postgres -p 5432 -U postgres postgres  <<SQL
#        DROP DATABASE airflow_db;
#        DROP OWNED BY airflow;
#        DROP USER airflow;
#        CREATE DATABASE airflow_db;
#        CREATE USER airflow WITH PASSWORD 'airflow';
#        GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow;
#        GRANT ALL ON SCHEMA public TO airflow;
#          ALTER USER airflow SET search_path = public;
#        SQL

  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: email@gmail.org
      PGADMIN_DEFAULT_PASSWORD: heslo
    ports:
      - "9999:80"
    depends_on:
      - postgres

  airflow_web:
    restart: always
    depends_on:
      - postgres
    build:
      context: compose
      dockerfile: ./webserver
    ports:
      - "8000:8080"
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=ddsaf3247
      - AIRFLOW__WEBSERVER__SECRET_KEY_SECRET=ddsaf3247
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_db

  airflow_scheduler:
    restart: always
    build:
      context: compose
      dockerfile: ./scheduler
    ports:
      - "8793:8793"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_db
      - AIRFLOW__WEBSERVER__SECRET_KEY=ddsaf3247
      - AIRFLOW__WEBSERVER__SECRET_KEY_SECRET=ddsaf3247
    depends_on:
      - postgres
